// ============================================
// CHAPTER LESSONS
// Same idea as lessons.js's PIECE_LESSONS, but for Midterm/Semifinal/
// Final — one short catechesis note per CHAPTER (not per node), shown
// the first time a student finishes every node in it. Grounded in
// "(Revised) Course Pack in ReEd 101 2025.docx" — every citation here
// (CCC numbers, Laudato Si', Scripture refs) was verified to appear
// in that source document, none invented. The two comprehensive-exam
// chapters (semifinal_ch7, final_ch11) get a capstone reflection
// instead of a sourced passage, since they're pure assessment, not
// new teaching content.
// ============================================

export const CHAPTER_LESSONS = {
  midterm_ch1: { title: "The Dawn of Salvation", text: "The Priestly account of creation in Genesis 1:1–2:4a is not merely the world's beginning but \"the basis for all of God's plans for salvation,\" finding its fulfillment in Jesus Christ (CCC 280)." },
  midterm_ch2: { title: "Someone, Not Something", text: "Because every person is made in God's image and likeness (Gen. 1:26–27; 2:4b–25), the Catechism affirms that a human being is always \"someone and not something\" — a dignity that is never earned by accomplishment or status (CCC 357)." },
  midterm_ch3: { title: "Tsedaqah and Mishpat", text: "Biblical justice lives in words like mishpat (right order) and tsedaqah (righteousness lived in relationship) — a justice that runs from Creation through the Exodus, the prophets, and the ministry of Jesus to the anawim, never as an abstract legal ideal." },
  semifinal_ch1: { title: "The Forbidden Tree", text: "The tree in the middle of the Garden symbolizes God's own Divine Goodness and sovereignty over life; the prohibition to eat from it means, in effect, \"Let God be God\" — a reminder that the fullness of life belongs to Him alone." },
  semifinal_ch2: { title: "Sin's Fourfold Wound", text: "After the Fall, sin unravels four relationships at once — shame estranges Adam and Eve from themselves (Gen. 3:7), guilt sends them hiding from God (Gen. 3:8), and Cain's envy destroys his bond with his own brother, showing how one broken relationship spreads to wound them all." },
  semifinal_ch3: { title: "The Sin of Idolatry", text: "Idolatry — elevating wealth, power, or pleasure to the place that belongs to God alone — stands in direct opposition to the First Commandment, \"You shall have no other gods before Me\" (Exodus 20:4–5), and it is the root from which heresy, hypocrisy, apostasy, and blasphemy all grow." },
  semifinal_ch4: { title: "Restless Until It Rests", text: "The builders of Babel sought \"to make a name\" for themselves apart from God (Gen. 11:4) — the same restless self-assertion that undid Adam and Eve — yet as St. Augustine confessed, \"You have made us for yourself, O Lord, and our hearts are restless until they rest in you.\"" },
  semifinal_ch5: { title: "Splendid Universal Communion", text: "Sin is not only a rupture between the sinner and God but a wound to creation itself; Pope Francis writes in Laudato Si' that \"we are not disconnected from the rest of creatures, but joined in a splendid universal communion\" (Laudato Si', §220), which is why healing the human heart and healing the earth belong together." },
  semifinal_ch6: { title: "Mortal and Venial Sin", text: "Tradition distinguishes venial sin, which wounds but does not sever the soul's friendship with God, from mortal sin, which requires grave matter, full knowledge, and deliberate consent, and which \"kills\" the life of grace within the believer (CCC 1857)." },
  semifinal_boss: { title: "The Father Who Waits", text: "You know the feeling: the lie that keeps you awake at night, the hurtful words you cannot take back, the thing you hide even from yourself. That heaviness is your conscience reminding you that you were made for something better.\n\nSin pulls us into the dark and makes us want to hide, but God never stops looking for us. Like the father of the prodigal son, He keeps watching the road: \"While he was still a long way off, his father caught sight of him, and was filled with compassion. He ran to his son, embraced him and kissed him\" (Lk 15:20).\n\n\"God never tires of forgiving us; we are the ones who tire of seeking his mercy\" (Pope Francis, Evangelii Gaudium, 3).\n\nWhatever you have done, turn back. In the Sacrament of Reconciliation, the light of conversion is waiting for you." },
  semifinal_ch7: { title: "Faith That Perseveres", text: "An exam does not measure how much of the story you can recite, but whether the story has taken root in you — let this be one more act of the perseverance that all of salvation history has been teaching you." },
  final_ch1: { title: "Total Salvation", text: "Salvation in Scripture is never only the soul's escape to heaven; it is the healing of the total person, the whole community, and all creation, reconciled through Christ's Incarnation and Paschal Mystery (CCC 1042–1045)." },
  final_redsea: { title: "A Way Through the Waters", text: "Maybe you know this feeling too: a problem in front of you that seems impossible, and something you cannot escape closing in from behind. Family troubles, failing grades, a habit you cannot break, fears you tell no one about. You feel trapped, with no way forward and no way back.\n\nThat is exactly where Israel stood, with the sea ahead and Pharaoh's army behind. And Moses said: \"Do not fear! Stand your ground and see the victory the LORD will win for you today… The LORD will fight for you\" (Ex 14:13–14). Then God did what no one thought possible: He made a path through the sea.\n\n\"When you pass through waters, I will be with you\" (Is 43:2). The Church sees in this crossing a sign of Baptism, through which God frees us from the slavery of sin (CCC 1221).\n\nWhen you feel trapped, do not give up. Turn to Him. The God who opened the sea can open a way for you." },
  final_ch2: { title: "Drawn From the Water", text: "Moses' very name means \"drawn out from the water\" — a sign that his life, and the escape of an enslaved people he would lead as guerilla fighter, teacher, and leader, was from its first moment an act of God's deliverance from death and oppression." },
  final_ch3: { title: "Faith from Lived History", text: "The Israelites summarized their entire history — from Abraham's migration through exile, return, and foreign rule — in a single creed recited at worship (Deut. 26:5–9; Psalm 105), because for them faith was never abstract but grew out of what God had concretely done for them in time." },
  final_ch4: { title: "The Sinai Covenant", text: "At Sinai the wandering tribes became the Qahal Yahweh, the assembly of the Lord, bound together by the Ten Commandments and by God's own covenant promise: \"I will be your God, and you shall be my people\" (Exodus 6:7; 20:2)." },
  final_sinai: { title: "The Freedom of Obedience", text: "Think of the times you were told what to do and did not want to follow. \"Be home by nine.\" \"Study first.\" \"Do not go with them.\" Obeying felt like losing. But think also of the times you did not listen, and what came after: the trouble you were warned about, the trust you had to rebuild, the quiet regret of \"I should have listened.\"\n\nWe do not follow just anyone. We follow those who have proven that they love us: the parent who stayed awake when we were sick, the teacher who believed in us, the friend who told us the truth. Obeying them is not weakness. It is trust.\n\nThat is why God first freed Israel, and only then gave the commandments: \"I am the LORD your God, who brought you out of the land of Egypt, out of the house of slavery\" (Ex 20:2). He earned their trust before He asked for their obedience. And what He asks is for our good. Moses told the people to follow \"the way that the LORD, your God, commanded you that you may live and prosper\" (Dt 5:33).\n\nTo obey means to listen: to submit freely to God's word because He is Truth itself (CCC 144). Jesus walked this road first, \"obedient to death, even death on a cross\" (Phil 2:8), and He tells us: \"If you love me, you will keep my commandments\" (Jn 14:15).\n\nLike the climb up Sinai, obedience is taken one step at a time. Today, when following is hard, take the next step anyway. The One who asks is the One who loves you most." },
  final_ch5: { title: "The Covenant Fulfilled", text: "Under Joshua and the Judges, Israel's covenant with Yahweh bore fruit in four concrete ways — possession of the land, growth into a nation, a shared identity as God's assembly, and freedom from foreign rule (Deut. 28:1–14; Joshua 24:13–15)." },
  final_ch6: { title: "A King's Covenant Duty", text: "Under Saul, David, and Solomon, Israel became a united and prosperous kingdom, yet Scripture insists a king's true task was \"upholding justice and preserving the covenant community\" as Yahweh's steward, not its owner (1 Samuel 12:14–15; Deuteronomy 17:18–20)." },
  final_goliath: { title: "Facing Your Giant", text: "Everyone has a Goliath. Maybe yours is a subject you keep failing, someone who puts you down, a problem at home that is bigger than you, or a voice inside that says, \"You are too small. You are not enough.\" Like the soldiers of Israel, we can stand frozen for days, measuring the giant and forgetting who stands with us.\n\nDavid was the youngest, a shepherd boy no one counted. Even the king told him he could not win. But David did not measure himself against Goliath. He measured Goliath against God: \"You come against me with sword and spear and scimitar, but I come against you in the name of the LORD of hosts\" (1 Sam 17:45). He remembered how God had already saved him from the lion and the bear, and that memory gave him courage.\n\nGod does not choose as the world chooses: \"The LORD looks into the heart\" (1 Sam 16:7). He does not ask you to be big. He asks you to trust Him and to use the little you have, your five smooth stones. This is fortitude, the virtue that gives us strength to conquer fear and to face our trials (CCC 1808).\n\nSo name your giant today. Remember what God has already brought you through, and step forward. \"The battle belongs to the LORD\" (1 Sam 17:47)." },
  final_temple: { title: "Built Stone by Stone", text: "Nothing worth having is built in a day. A friendship, your parents' trust, a good habit, a passing grade after a failing one: each is laid one stone at a time. And you know how it feels when a careless moment knocks some of it down. One lie, one harsh word, one \"just this once,\" and what took months to build becomes smaller.\n\nSolomon's Temple was built the same way. It took seven years (1 Kgs 6:38), with every stone prepared with care before it was set in place. And when it was finished, God filled it with His glory, because He wanted to dwell among His people.\n\nBut God wanted an even closer home than a building of stone. \"Do you not know that you are the temple of God, and that the Spirit of God dwells in you?\" (1 Cor 3:16). Your own body and life are meant to become a temple of the Spirit (CCC 364). Every honest answer, every prayer, every act of kindness, every time you say no to what would harm you is a stone set in place.\n\nAnd when a stone cracks, the Builder does not walk away. He invites you to begin again, with Him: \"Unless the LORD build the house, they labor in vain who build\" (Ps 127:1).\n\nWhat stone will you set today?" },
  final_ch7: { title: "The Cost of Disunity", text: "When Solomon's heavy taxes and forced labor fractured the united kingdom into Israel and Judah, the division itself became a lesson: it was covenant loyalty to Yahweh, not political strength alone, that had held the nation together, and its absence left both kingdoms open to conquest and exile." },
  final_siege: { title: "When the Walls Come Down", text: "There are things we believe will always stand: our family as it is, a friendship, our health, the plans we made, the picture we had of ourselves. Then one day a wall comes down. Parents separate. Someone we love dies. We fail at the thing we worked hardest for. Sometimes, as with Judah, the prophets had warned us and we did not listen, and part of the ruin is our own doing.\n\nJerusalem's fall felt like the end of everything. The Temple burned, the king was taken, and the people were marched to a foreign land. It looked as if God had abandoned His promises.\n\nBut He had not. In the ruins someone still prayed: \"The LORD's acts of mercy are not exhausted, his compassion is not spent; they are renewed each morning\" (Lam 3:22–23). And to the exiles God sent this word: \"I know well the plans I have in mind for you, plans for your welfare and not for woe, so as to give you a future of hope\" (Jer 29:11). The Exile, which looked like the failure of God's promises, was in fact the beginning of a promised restoration (CCC 710).\n\nWhen your walls come down, do not conclude that God has left. Bring Him the ruins, and what was your fault with them. He builds again from a remnant, and He is not finished with you." },
  final_ch8: { title: "Word, Deed, and Death", text: "The prophets carried out a threefold task — to proclaim the Word of God, to confirm it with deeds and signs, and, for many, to endure a martyr's death — passing through stages of calling, protest, bargaining, and acceptance before taking up that mission." },
  final_ch9: { title: "Cyrus and the Return", text: "When Persia's King Cyrus issued the decree allowing the exiled Israelites to return home (Ezra 1:1–4), the rebuilding of the Temple under Zerubbabel, Ezra, and Nehemiah became a sign that God had not forgotten His covenant even after the discipline of exile." },
  final_ch10: { title: "Faith Under Persecution", text: "When Antiochus IV Epiphanes desecrated the Temple and outlawed circumcision and Sabbath observance, the Maccabean family's revolt won Israel nearly a century of uneasy independence — proof, as the record of their struggle affirms, of God's power at work in His chosen ones." },
  final_ch11: { title: "The Whole Story", text: "From the seven days of creation to the birth of Jesus into a world still waiting for Him, you have traced one continuous story of a God who never abandons what He has made — let this final exam be less an ending than a beginning of carrying that story forward." }
};
