// ============================================
// CHAPTER LESSONS
// Same idea as lessons.js's PIECE_LESSONS, but for Midterm/Semifinal/
// Final — one short catechesis note per CHAPTER (not per node), shown
// the first time a student finishes every node in it. Grounded in
// "(Revised) Course Pack in ReEd 101 2025.docx" — every citation here
// (CCC numbers, Laudato Si', Scripture refs) was verified to appear
// in that source document, none invented. The two comprehensive-exam
// chapters (semifinal_ch7, final_ch11) get a capstone reflection
// instead of a sourced passage, since they're pure assessment, not
// new teaching content.
// ============================================

export const CHAPTER_LESSONS = {
  midterm_ch1: { title: "The Dawn of Salvation", text: "The Priestly account of creation in Genesis 1:1–2:4a is not merely the world's beginning but \"the basis for all of God's plans for salvation,\" finding its fulfillment in Jesus Christ (CCC 280)." },
  midterm_ch2: { title: "Someone, Not Something", text: "Because every person is made in God's image and likeness (Gen. 1:26–27; 2:4b–25), the Catechism affirms that a human being is always \"someone and not something\" — a dignity that is never earned by accomplishment or status (CCC 357)." },
  midterm_ch3: { title: "Tsedaqah and Mishpat", text: "Biblical justice lives in words like mishpat (right order) and tsedaqah (righteousness lived in relationship) — a justice that runs from Creation through the Exodus, the prophets, and the ministry of Jesus to the anawim, never as an abstract legal ideal." },
  semifinal_ch1: { title: "The Forbidden Tree", text: "The tree in the middle of the Garden symbolizes God's own Divine Goodness and sovereignty over life; the prohibition to eat from it means, in effect, \"Let God be God\" — a reminder that the fullness of life belongs to Him alone." },
  semifinal_ch2: { title: "Sin's Fourfold Wound", text: "After the Fall, sin unravels four relationships at once — shame estranges Adam and Eve from themselves (Gen. 3:7), guilt sends them hiding from God (Gen. 3:8), and Cain's envy destroys his bond with his own brother, showing how one broken relationship spreads to wound them all." },
  semifinal_ch3: { title: "The Sin of Idolatry", text: "Idolatry — elevating wealth, power, or pleasure to the place that belongs to God alone — stands in direct opposition to the First Commandment, \"You shall have no other gods before Me\" (Exodus 20:4–5), and it is the root from which heresy, hypocrisy, apostasy, and blasphemy all grow." },
  semifinal_ch4: { title: "Restless Until It Rests", text: "The builders of Babel sought \"to make a name\" for themselves apart from God (Gen. 11:4) — the same restless self-assertion that undid Adam and Eve — yet as St. Augustine confessed, \"You have made us for yourself, O Lord, and our hearts are restless until they rest in you.\"" },
  semifinal_ch5: { title: "Splendid Universal Communion", text: "Sin is not only a rupture between the sinner and God but a wound to creation itself; Pope Francis writes in Laudato Si' that \"we are not disconnected from the rest of creatures, but joined in a splendid universal communion\" (Laudato Si', §220), which is why healing the human heart and healing the earth belong together." },
  semifinal_ch6: { title: "Mortal and Venial Sin", text: "Tradition distinguishes venial sin, which wounds but does not sever the soul's friendship with God, from mortal sin, which requires grave matter, full knowledge, and deliberate consent, and which \"kills\" the life of grace within the believer (CCC 1857)." },
  semifinal_ch7: { title: "Faith That Perseveres", text: "An exam does not measure how much of the story you can recite, but whether the story has taken root in you — let this be one more act of the perseverance that all of salvation history has been teaching you." },
  final_ch1: { title: "Total Salvation", text: "Salvation in Scripture is never only the soul's escape to heaven; it is the healing of the total person, the whole community, and all creation, reconciled through Christ's Incarnation and Paschal Mystery (CCC 1042–1045)." },
  final_ch2: { title: "Drawn From the Water", text: "Moses' very name means \"drawn out from the water\" — a sign that his life, and the escape of an enslaved people he would lead as guerilla fighter, teacher, and leader, was from its first moment an act of God's deliverance from death and oppression." },
  final_ch3: { title: "Faith from Lived History", text: "The Israelites summarized their entire history — from Abraham's migration through exile, return, and foreign rule — in a single creed recited at worship (Deut. 26:5–9; Psalm 105), because for them faith was never abstract but grew out of what God had concretely done for them in time." },
  final_ch4: { title: "The Sinai Covenant", text: "At Sinai the wandering tribes became the Qahal Yahweh, the assembly of the Lord, bound together by the Ten Commandments and by God's own covenant promise: \"I will be your God, and you shall be my people\" (Exodus 6:7; 20:2)." },
  final_ch5: { title: "The Covenant Fulfilled", text: "Under Joshua and the Judges, Israel's covenant with Yahweh bore fruit in four concrete ways — possession of the land, growth into a nation, a shared identity as God's assembly, and freedom from foreign rule (Deut. 28:1–14; Joshua 24:13–15)." },
  final_ch6: { title: "A King's Covenant Duty", text: "Under Saul, David, and Solomon, Israel became a united and prosperous kingdom, yet Scripture insists a king's true task was \"upholding justice and preserving the covenant community\" as Yahweh's steward, not its owner (1 Samuel 12:14–15; Deuteronomy 17:18–20)." },
  final_ch7: { title: "The Cost of Disunity", text: "When Solomon's heavy taxes and forced labor fractured the united kingdom into Israel and Judah, the division itself became a lesson: it was covenant loyalty to Yahweh, not political strength alone, that had held the nation together, and its absence left both kingdoms open to conquest and exile." },
  final_ch8: { title: "Word, Deed, and Death", text: "The prophets carried out a threefold task — to proclaim the Word of God, to confirm it with deeds and signs, and, for many, to endure a martyr's death — passing through stages of calling, protest, bargaining, and acceptance before taking up that mission." },
  final_ch9: { title: "Cyrus and the Return", text: "When Persia's King Cyrus issued the decree allowing the exiled Israelites to return home (Ezra 1:1–4), the rebuilding of the Temple under Zerubbabel, Ezra, and Nehemiah became a sign that God had not forgotten His covenant even after the discipline of exile." },
  final_ch10: { title: "Faith Under Persecution", text: "When Antiochus IV Epiphanes desecrated the Temple and outlawed circumcision and Sabbath observance, the Maccabean family's revolt won Israel nearly a century of uneasy independence — proof, as the record of their struggle affirms, of God's power at work in His chosen ones." },
  final_ch11: { title: "The Whole Story", text: "From the seven days of creation to the birth of Jesus into a world still waiting for Him, you have traced one continuous story of a God who never abandons what He has made — let this final exam be less an ending than a beginning of carrying that story forward." }
};
